// ============================================================
// Quran Structure Data — All 30 Juz, 114 Surahs
// ============================================================

export interface ParaInfo {
  paraNumber: number;
  name: string;
  arabicName: string;
  startSurah: number;
  startAyah: number;
}

export interface SurahInfo {
  surahNumber: number;
  name: string;
  arabicName: string;
  totalAyah: number;
  paraNumber: number; // which para this surah starts in
}

export const PARA_LIST: ParaInfo[] = [
  {
    paraNumber: 1,
    name: "Alif Lam Meem",
    arabicName: "الم",
    startSurah: 1,
    startAyah: 1,
  },
  {
    paraNumber: 2,
    name: "Sayaqul",
    arabicName: "سيقول",
    startSurah: 2,
    startAyah: 142,
  },
  {
    paraNumber: 3,
    name: "Tilkar Rusul",
    arabicName: "تلك الرسل",
    startSurah: 2,
    startAyah: 253,
  },
  {
    paraNumber: 4,
    name: "Lan Tana Lu",
    arabicName: "لن تنالوا",
    startSurah: 3,
    startAyah: 92,
  },
  {
    paraNumber: 5,
    name: "Wal Muhsanat",
    arabicName: "والمحصنات",
    startSurah: 4,
    startAyah: 24,
  },
  {
    paraNumber: 6,
    name: "La Yuhibbullah",
    arabicName: "لا يحب الله",
    startSurah: 4,
    startAyah: 148,
  },
  {
    paraNumber: 7,
    name: "Wa Iza Samiu",
    arabicName: "وإذا سمعوا",
    startSurah: 5,
    startAyah: 82,
  },
  {
    paraNumber: 8,
    name: "Wa Law Annana",
    arabicName: "ولو أننا",
    startSurah: 6,
    startAyah: 111,
  },
  {
    paraNumber: 9,
    name: "Qalal Mala",
    arabicName: "قال الملأ",
    startSurah: 7,
    startAyah: 88,
  },
  {
    paraNumber: 10,
    name: "Wa A'lamu",
    arabicName: "واعلموا",
    startSurah: 8,
    startAyah: 41,
  },
  {
    paraNumber: 11,
    name: "Ya'taziruna",
    arabicName: "يعتذرون",
    startSurah: 9,
    startAyah: 93,
  },
  {
    paraNumber: 12,
    name: "Wa Ma Min Dabbah",
    arabicName: "وما من دابة",
    startSurah: 11,
    startAyah: 6,
  },
  {
    paraNumber: 13,
    name: "Wa Ma Ubarri'u",
    arabicName: "وما أبرئ",
    startSurah: 12,
    startAyah: 53,
  },
  {
    paraNumber: 14,
    name: "Rubama",
    arabicName: "ربما",
    startSurah: 15,
    startAyah: 1,
  },
  {
    paraNumber: 15,
    name: "Subhanallazi",
    arabicName: "سبحان الذي",
    startSurah: 17,
    startAyah: 1,
  },
  {
    paraNumber: 16,
    name: "Qala Alam",
    arabicName: "قال ألم",
    startSurah: 18,
    startAyah: 75,
  },
  {
    paraNumber: 17,
    name: "Iqtaraba",
    arabicName: "اقترب",
    startSurah: 21,
    startAyah: 1,
  },
  {
    paraNumber: 18,
    name: "Qad Aflaha",
    arabicName: "قد أفلح",
    startSurah: 23,
    startAyah: 1,
  },
  {
    paraNumber: 19,
    name: "Wa Qalallazina",
    arabicName: "وقال الذين",
    startSurah: 25,
    startAyah: 21,
  },
  {
    paraNumber: 20,
    name: "A'man Khalaq",
    arabicName: "أمن خلق",
    startSurah: 27,
    startAyah: 56,
  },
  {
    paraNumber: 21,
    name: "Utlu Ma Uhiya",
    arabicName: "اتل ما أوحي",
    startSurah: 29,
    startAyah: 46,
  },
  {
    paraNumber: 22,
    name: "Wa Man Yaqnut",
    arabicName: "ومن يقنت",
    startSurah: 33,
    startAyah: 31,
  },
  {
    paraNumber: 23,
    name: "Wa Mali",
    arabicName: "وما لي",
    startSurah: 36,
    startAyah: 28,
  },
  {
    paraNumber: 24,
    name: "Fa Man Azlam",
    arabicName: "فمن أظلم",
    startSurah: 39,
    startAyah: 32,
  },
  {
    paraNumber: 25,
    name: "Ilayhi Yuraddu",
    arabicName: "إليه يرد",
    startSurah: 41,
    startAyah: 47,
  },
  {
    paraNumber: 26,
    name: "Ha Meem",
    arabicName: "حم",
    startSurah: 46,
    startAyah: 1,
  },
  {
    paraNumber: 27,
    name: "Qala Fama Khatbukum",
    arabicName: "قال فما خطبكم",
    startSurah: 51,
    startAyah: 31,
  },
  {
    paraNumber: 28,
    name: "Qad Sami Allah",
    arabicName: "قد سمع الله",
    startSurah: 58,
    startAyah: 1,
  },
  {
    paraNumber: 29,
    name: "Tabarakallazi",
    arabicName: "تبارك الذي",
    startSurah: 67,
    startAyah: 1,
  },
  {
    paraNumber: 30,
    name: "Amma",
    arabicName: "عم",
    startSurah: 78,
    startAyah: 1,
  },
];

export const SURAH_LIST: SurahInfo[] = [
  {
    surahNumber: 1,
    name: "Al-Fatiha",
    arabicName: "الفاتحة",
    totalAyah: 7,
    paraNumber: 1,
  },
  {
    surahNumber: 2,
    name: "Al-Baqarah",
    arabicName: "البقرة",
    totalAyah: 286,
    paraNumber: 1,
  },
  {
    surahNumber: 3,
    name: "Al-Imran",
    arabicName: "آل عمران",
    totalAyah: 200,
    paraNumber: 3,
  },
  {
    surahNumber: 4,
    name: "An-Nisa",
    arabicName: "النساء",
    totalAyah: 176,
    paraNumber: 4,
  },
  {
    surahNumber: 5,
    name: "Al-Ma'idah",
    arabicName: "المائدة",
    totalAyah: 120,
    paraNumber: 6,
  },
  {
    surahNumber: 6,
    name: "Al-An'am",
    arabicName: "الأنعام",
    totalAyah: 165,
    paraNumber: 7,
  },
  {
    surahNumber: 7,
    name: "Al-A'raf",
    arabicName: "الأعراف",
    totalAyah: 206,
    paraNumber: 8,
  },
  {
    surahNumber: 8,
    name: "Al-Anfal",
    arabicName: "الأنفال",
    totalAyah: 75,
    paraNumber: 9,
  },
  {
    surahNumber: 9,
    name: "At-Tawbah",
    arabicName: "التوبة",
    totalAyah: 129,
    paraNumber: 10,
  },
  {
    surahNumber: 10,
    name: "Yunus",
    arabicName: "يونس",
    totalAyah: 109,
    paraNumber: 11,
  },
  {
    surahNumber: 11,
    name: "Hud",
    arabicName: "هود",
    totalAyah: 123,
    paraNumber: 11,
  },
  {
    surahNumber: 12,
    name: "Yusuf",
    arabicName: "يوسف",
    totalAyah: 111,
    paraNumber: 12,
  },
  {
    surahNumber: 13,
    name: "Ar-Ra'd",
    arabicName: "الرعد",
    totalAyah: 43,
    paraNumber: 13,
  },
  {
    surahNumber: 14,
    name: "Ibrahim",
    arabicName: "إبراهيم",
    totalAyah: 52,
    paraNumber: 13,
  },
  {
    surahNumber: 15,
    name: "Al-Hijr",
    arabicName: "الحجر",
    totalAyah: 99,
    paraNumber: 14,
  },
  {
    surahNumber: 16,
    name: "An-Nahl",
    arabicName: "النحل",
    totalAyah: 128,
    paraNumber: 14,
  },
  {
    surahNumber: 17,
    name: "Al-Isra",
    arabicName: "الإسراء",
    totalAyah: 111,
    paraNumber: 15,
  },
  {
    surahNumber: 18,
    name: "Al-Kahf",
    arabicName: "الكهف",
    totalAyah: 110,
    paraNumber: 15,
  },
  {
    surahNumber: 19,
    name: "Maryam",
    arabicName: "مريم",
    totalAyah: 98,
    paraNumber: 16,
  },
  {
    surahNumber: 20,
    name: "Ta-Ha",
    arabicName: "طه",
    totalAyah: 135,
    paraNumber: 16,
  },
  {
    surahNumber: 21,
    name: "Al-Anbiya",
    arabicName: "الأنبياء",
    totalAyah: 112,
    paraNumber: 17,
  },
  {
    surahNumber: 22,
    name: "Al-Hajj",
    arabicName: "الحج",
    totalAyah: 78,
    paraNumber: 17,
  },
  {
    surahNumber: 23,
    name: "Al-Mu'minun",
    arabicName: "المؤمنون",
    totalAyah: 118,
    paraNumber: 18,
  },
  {
    surahNumber: 24,
    name: "An-Nur",
    arabicName: "النور",
    totalAyah: 64,
    paraNumber: 18,
  },
  {
    surahNumber: 25,
    name: "Al-Furqan",
    arabicName: "الفرقان",
    totalAyah: 77,
    paraNumber: 18,
  },
  {
    surahNumber: 26,
    name: "Ash-Shu'ara",
    arabicName: "الشعراء",
    totalAyah: 227,
    paraNumber: 19,
  },
  {
    surahNumber: 27,
    name: "An-Naml",
    arabicName: "النمل",
    totalAyah: 93,
    paraNumber: 19,
  },
  {
    surahNumber: 28,
    name: "Al-Qasas",
    arabicName: "القصص",
    totalAyah: 88,
    paraNumber: 20,
  },
  {
    surahNumber: 29,
    name: "Al-Ankabut",
    arabicName: "العنكبوت",
    totalAyah: 69,
    paraNumber: 20,
  },
  {
    surahNumber: 30,
    name: "Ar-Rum",
    arabicName: "الروم",
    totalAyah: 60,
    paraNumber: 21,
  },
  {
    surahNumber: 31,
    name: "Luqman",
    arabicName: "لقمان",
    totalAyah: 34,
    paraNumber: 21,
  },
  {
    surahNumber: 32,
    name: "As-Sajdah",
    arabicName: "السجدة",
    totalAyah: 30,
    paraNumber: 21,
  },
  {
    surahNumber: 33,
    name: "Al-Ahzab",
    arabicName: "الأحزاب",
    totalAyah: 73,
    paraNumber: 21,
  },
  {
    surahNumber: 34,
    name: "Saba",
    arabicName: "سبأ",
    totalAyah: 54,
    paraNumber: 22,
  },
  {
    surahNumber: 35,
    name: "Fatir",
    arabicName: "فاطر",
    totalAyah: 45,
    paraNumber: 22,
  },
  {
    surahNumber: 36,
    name: "Ya-Sin",
    arabicName: "يس",
    totalAyah: 83,
    paraNumber: 22,
  },
  {
    surahNumber: 37,
    name: "As-Saffat",
    arabicName: "الصافات",
    totalAyah: 182,
    paraNumber: 23,
  },
  {
    surahNumber: 38,
    name: "Sad",
    arabicName: "ص",
    totalAyah: 88,
    paraNumber: 23,
  },
  {
    surahNumber: 39,
    name: "Az-Zumar",
    arabicName: "الزمر",
    totalAyah: 75,
    paraNumber: 23,
  },
  {
    surahNumber: 40,
    name: "Ghafir",
    arabicName: "غافر",
    totalAyah: 85,
    paraNumber: 24,
  },
  {
    surahNumber: 41,
    name: "Fussilat",
    arabicName: "فصلت",
    totalAyah: 54,
    paraNumber: 24,
  },
  {
    surahNumber: 42,
    name: "Ash-Shura",
    arabicName: "الشورى",
    totalAyah: 53,
    paraNumber: 25,
  },
  {
    surahNumber: 43,
    name: "Az-Zukhruf",
    arabicName: "الزخرف",
    totalAyah: 89,
    paraNumber: 25,
  },
  {
    surahNumber: 44,
    name: "Ad-Dukhan",
    arabicName: "الدخان",
    totalAyah: 59,
    paraNumber: 25,
  },
  {
    surahNumber: 45,
    name: "Al-Jathiyah",
    arabicName: "الجاثية",
    totalAyah: 37,
    paraNumber: 25,
  },
  {
    surahNumber: 46,
    name: "Al-Ahqaf",
    arabicName: "الأحقاف",
    totalAyah: 35,
    paraNumber: 26,
  },
  {
    surahNumber: 47,
    name: "Muhammad",
    arabicName: "محمد",
    totalAyah: 38,
    paraNumber: 26,
  },
  {
    surahNumber: 48,
    name: "Al-Fath",
    arabicName: "الفتح",
    totalAyah: 29,
    paraNumber: 26,
  },
  {
    surahNumber: 49,
    name: "Al-Hujurat",
    arabicName: "الحجرات",
    totalAyah: 18,
    paraNumber: 26,
  },
  {
    surahNumber: 50,
    name: "Qaf",
    arabicName: "ق",
    totalAyah: 45,
    paraNumber: 26,
  },
  {
    surahNumber: 51,
    name: "Adh-Dhariyat",
    arabicName: "الذاريات",
    totalAyah: 60,
    paraNumber: 26,
  },
  {
    surahNumber: 52,
    name: "At-Tur",
    arabicName: "الطور",
    totalAyah: 49,
    paraNumber: 27,
  },
  {
    surahNumber: 53,
    name: "An-Najm",
    arabicName: "النجم",
    totalAyah: 62,
    paraNumber: 27,
  },
  {
    surahNumber: 54,
    name: "Al-Qamar",
    arabicName: "القمر",
    totalAyah: 55,
    paraNumber: 27,
  },
  {
    surahNumber: 55,
    name: "Ar-Rahman",
    arabicName: "الرحمن",
    totalAyah: 78,
    paraNumber: 27,
  },
  {
    surahNumber: 56,
    name: "Al-Waqi'ah",
    arabicName: "الواقعة",
    totalAyah: 96,
    paraNumber: 27,
  },
  {
    surahNumber: 57,
    name: "Al-Hadid",
    arabicName: "الحديد",
    totalAyah: 29,
    paraNumber: 27,
  },
  {
    surahNumber: 58,
    name: "Al-Mujadila",
    arabicName: "المجادلة",
    totalAyah: 22,
    paraNumber: 28,
  },
  {
    surahNumber: 59,
    name: "Al-Hashr",
    arabicName: "الحشر",
    totalAyah: 24,
    paraNumber: 28,
  },
  {
    surahNumber: 60,
    name: "Al-Mumtahanah",
    arabicName: "الممتحنة",
    totalAyah: 13,
    paraNumber: 28,
  },
  {
    surahNumber: 61,
    name: "As-Saf",
    arabicName: "الصف",
    totalAyah: 14,
    paraNumber: 28,
  },
  {
    surahNumber: 62,
    name: "Al-Jumu'ah",
    arabicName: "الجمعة",
    totalAyah: 11,
    paraNumber: 28,
  },
  {
    surahNumber: 63,
    name: "Al-Munafiqun",
    arabicName: "المنافقون",
    totalAyah: 11,
    paraNumber: 28,
  },
  {
    surahNumber: 64,
    name: "At-Taghabun",
    arabicName: "التغابن",
    totalAyah: 18,
    paraNumber: 28,
  },
  {
    surahNumber: 65,
    name: "At-Talaq",
    arabicName: "الطلاق",
    totalAyah: 12,
    paraNumber: 28,
  },
  {
    surahNumber: 66,
    name: "At-Tahrim",
    arabicName: "التحريم",
    totalAyah: 12,
    paraNumber: 28,
  },
  {
    surahNumber: 67,
    name: "Al-Mulk",
    arabicName: "الملك",
    totalAyah: 30,
    paraNumber: 29,
  },
  {
    surahNumber: 68,
    name: "Al-Qalam",
    arabicName: "القلم",
    totalAyah: 52,
    paraNumber: 29,
  },
  {
    surahNumber: 69,
    name: "Al-Haqqah",
    arabicName: "الحاقة",
    totalAyah: 52,
    paraNumber: 29,
  },
  {
    surahNumber: 70,
    name: "Al-Ma'arij",
    arabicName: "المعارج",
    totalAyah: 44,
    paraNumber: 29,
  },
  {
    surahNumber: 71,
    name: "Nuh",
    arabicName: "نوح",
    totalAyah: 28,
    paraNumber: 29,
  },
  {
    surahNumber: 72,
    name: "Al-Jinn",
    arabicName: "الجن",
    totalAyah: 28,
    paraNumber: 29,
  },
  {
    surahNumber: 73,
    name: "Al-Muzzammil",
    arabicName: "المزمل",
    totalAyah: 20,
    paraNumber: 29,
  },
  {
    surahNumber: 74,
    name: "Al-Muddaththir",
    arabicName: "المدثر",
    totalAyah: 56,
    paraNumber: 29,
  },
  {
    surahNumber: 75,
    name: "Al-Qiyamah",
    arabicName: "القيامة",
    totalAyah: 40,
    paraNumber: 29,
  },
  {
    surahNumber: 76,
    name: "Al-Insan",
    arabicName: "الإنسان",
    totalAyah: 31,
    paraNumber: 29,
  },
  {
    surahNumber: 77,
    name: "Al-Mursalat",
    arabicName: "المرسلات",
    totalAyah: 50,
    paraNumber: 29,
  },
  {
    surahNumber: 78,
    name: "An-Naba",
    arabicName: "النبأ",
    totalAyah: 40,
    paraNumber: 30,
  },
  {
    surahNumber: 79,
    name: "An-Nazi'at",
    arabicName: "النازعات",
    totalAyah: 46,
    paraNumber: 30,
  },
  {
    surahNumber: 80,
    name: "Abasa",
    arabicName: "عبس",
    totalAyah: 42,
    paraNumber: 30,
  },
  {
    surahNumber: 81,
    name: "At-Takwir",
    arabicName: "التكوير",
    totalAyah: 29,
    paraNumber: 30,
  },
  {
    surahNumber: 82,
    name: "Al-Infitar",
    arabicName: "الانفطار",
    totalAyah: 19,
    paraNumber: 30,
  },
  {
    surahNumber: 83,
    name: "Al-Mutaffifin",
    arabicName: "المطففين",
    totalAyah: 36,
    paraNumber: 30,
  },
  {
    surahNumber: 84,
    name: "Al-Inshiqaq",
    arabicName: "الانشقاق",
    totalAyah: 25,
    paraNumber: 30,
  },
  {
    surahNumber: 85,
    name: "Al-Buruj",
    arabicName: "البروج",
    totalAyah: 22,
    paraNumber: 30,
  },
  {
    surahNumber: 86,
    name: "At-Tariq",
    arabicName: "الطارق",
    totalAyah: 17,
    paraNumber: 30,
  },
  {
    surahNumber: 87,
    name: "Al-A'la",
    arabicName: "الأعلى",
    totalAyah: 19,
    paraNumber: 30,
  },
  {
    surahNumber: 88,
    name: "Al-Ghashiyah",
    arabicName: "الغاشية",
    totalAyah: 26,
    paraNumber: 30,
  },
  {
    surahNumber: 89,
    name: "Al-Fajr",
    arabicName: "الفجر",
    totalAyah: 30,
    paraNumber: 30,
  },
  {
    surahNumber: 90,
    name: "Al-Balad",
    arabicName: "البلد",
    totalAyah: 20,
    paraNumber: 30,
  },
  {
    surahNumber: 91,
    name: "Ash-Shams",
    arabicName: "الشمس",
    totalAyah: 15,
    paraNumber: 30,
  },
  {
    surahNumber: 92,
    name: "Al-Layl",
    arabicName: "الليل",
    totalAyah: 21,
    paraNumber: 30,
  },
  {
    surahNumber: 93,
    name: "Ad-Duha",
    arabicName: "الضحى",
    totalAyah: 11,
    paraNumber: 30,
  },
  {
    surahNumber: 94,
    name: "Ash-Sharh",
    arabicName: "الشرح",
    totalAyah: 8,
    paraNumber: 30,
  },
  {
    surahNumber: 95,
    name: "At-Tin",
    arabicName: "التين",
    totalAyah: 8,
    paraNumber: 30,
  },
  {
    surahNumber: 96,
    name: "Al-Alaq",
    arabicName: "العلق",
    totalAyah: 19,
    paraNumber: 30,
  },
  {
    surahNumber: 97,
    name: "Al-Qadr",
    arabicName: "القدر",
    totalAyah: 5,
    paraNumber: 30,
  },
  {
    surahNumber: 98,
    name: "Al-Bayyinah",
    arabicName: "البينة",
    totalAyah: 8,
    paraNumber: 30,
  },
  {
    surahNumber: 99,
    name: "Az-Zalzalah",
    arabicName: "الزلزلة",
    totalAyah: 8,
    paraNumber: 30,
  },
  {
    surahNumber: 100,
    name: "Al-Adiyat",
    arabicName: "العاديات",
    totalAyah: 11,
    paraNumber: 30,
  },
  {
    surahNumber: 101,
    name: "Al-Qari'ah",
    arabicName: "القارعة",
    totalAyah: 11,
    paraNumber: 30,
  },
  {
    surahNumber: 102,
    name: "At-Takathur",
    arabicName: "التكاثر",
    totalAyah: 8,
    paraNumber: 30,
  },
  {
    surahNumber: 103,
    name: "Al-Asr",
    arabicName: "العصر",
    totalAyah: 3,
    paraNumber: 30,
  },
  {
    surahNumber: 104,
    name: "Al-Humazah",
    arabicName: "الهمزة",
    totalAyah: 9,
    paraNumber: 30,
  },
  {
    surahNumber: 105,
    name: "Al-Fil",
    arabicName: "الفيل",
    totalAyah: 5,
    paraNumber: 30,
  },
  {
    surahNumber: 106,
    name: "Quraysh",
    arabicName: "قريش",
    totalAyah: 4,
    paraNumber: 30,
  },
  {
    surahNumber: 107,
    name: "Al-Ma'un",
    arabicName: "الماعون",
    totalAyah: 7,
    paraNumber: 30,
  },
  {
    surahNumber: 108,
    name: "Al-Kawthar",
    arabicName: "الكوثر",
    totalAyah: 3,
    paraNumber: 30,
  },
  {
    surahNumber: 109,
    name: "Al-Kafirun",
    arabicName: "الكافرون",
    totalAyah: 6,
    paraNumber: 30,
  },
  {
    surahNumber: 110,
    name: "An-Nasr",
    arabicName: "النصر",
    totalAyah: 3,
    paraNumber: 30,
  },
  {
    surahNumber: 111,
    name: "Al-Masad",
    arabicName: "المسد",
    totalAyah: 5,
    paraNumber: 30,
  },
  {
    surahNumber: 112,
    name: "Al-Ikhlas",
    arabicName: "الإخلاص",
    totalAyah: 4,
    paraNumber: 30,
  },
  {
    surahNumber: 113,
    name: "Al-Falaq",
    arabicName: "الفلق",
    totalAyah: 5,
    paraNumber: 30,
  },
  {
    surahNumber: 114,
    name: "An-Nas",
    arabicName: "الناس",
    totalAyah: 6,
    paraNumber: 30,
  },
];

// ============================================================
// Helper Functions
// ============================================================

/**
 * Returns all surahs that belong to the given para (juz) number.
 */
export function getSurahsInPara(paraNumber: number): SurahInfo[] {
  return SURAH_LIST.filter((s) => s.paraNumber === paraNumber);
}

/**
 * Returns the ParaInfo for the para in which the given surah starts.
 */
export function getParaForSurah(surahNumber: number): ParaInfo | undefined {
  const surah = SURAH_LIST.find((s) => s.surahNumber === surahNumber);
  if (!surah) return undefined;
  return PARA_LIST.find((p) => p.paraNumber === surah.paraNumber);
}
