/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Ayat = IDL.Record({
  'surahNumber' : IDL.Nat,
  'hindi' : IDL.Text,
  'surahName' : IDL.Text,
  'urdu' : IDL.Text,
  'surahNameArabic' : IDL.Text,
  'arabic' : IDL.Text,
  'ayatNumber' : IDL.Nat,
  'english' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAyatByIndex' : IDL.Func([IDL.Nat], [Ayat], ['query']),
  'getDayIndex' : IDL.Func([], [IDL.Int], ['query']),
  'getTodayAyat' : IDL.Func([], [Ayat], ['query']),
  'getTotalAyat' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Ayat = IDL.Record({
    'surahNumber' : IDL.Nat,
    'hindi' : IDL.Text,
    'surahName' : IDL.Text,
    'urdu' : IDL.Text,
    'surahNameArabic' : IDL.Text,
    'arabic' : IDL.Text,
    'ayatNumber' : IDL.Nat,
    'english' : IDL.Text,
  });
  
  return IDL.Service({
    'getAyatByIndex' : IDL.Func([IDL.Nat], [Ayat], ['query']),
    'getDayIndex' : IDL.Func([], [IDL.Int], ['query']),
    'getTodayAyat' : IDL.Func([], [Ayat], ['query']),
    'getTotalAyat' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };